display = "A/V Tech Room A"
clientId = "0000-0004"
rxGroups = ["av-tech", "room-a"]
txGroups = []
buttonSets = ["av-tech"]

[buttons.6]
display = "Room A Broadcast"
target = "room-a"
targetType = "GROUP"
action = "PUSH"
direction = "TX"
