display = "A/V Tech Room B"
clientId = "0000-0005"
rxGroups = ["av-tech", "room-b"]
txGroups = []
buttonSets = ["av-tech"]

[buttons.6]
display = "Room B Broadcast"
target = "room-b"
targetType = "GROUP"
