display="A/V Tech Romm A"
rxGroups=["room-a", "av-tech"]
txGroups=["av-tech"]
buttonsets=["av-tech"]
hostId="0000-0004"

[buttons.6]
display="Room A Broadcast"
action="ptt"
targetType="group"
target="room-a"
