[buttons.1]
display="A/V Tech Broadcast"
action="push"
targetType="group"
target="av-tech"

[buttons.2]
display="Room A Broadcast"
action="push"
targetType="group"
target="room-a"

[buttons.3]
display="Room B Broadcast"
action="push"
targetType="group"
target="room-b"

[buttons.4]
display="Helpdesk Broadcast"
action="push"
targetType="group"
target="helpdesk"

#######

[buttons.5]
display="A/V Tech Room A"
action="push"
targetType="panel"
target="av-tech-room-a"

[buttons.6]
display="A/V Tech Room B"
action="push"
targetType="panel"
target="av-tech-room-b"
